language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sqwidget' ]; then cd .. && eval "mv $currentfolder generator-sqwidget" && cd generator-sqwidget; fi

